---
# Copyright 2022 City Network International AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Gather variables for each operating system
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - always

- import_tasks: zookeeper_pre_install.yml
  tags:
    - zookeeper-install

- import_tasks: zookeeper_install.yml
  tags:
    - zookeeper-install

- import_tasks: zookeeper_post_install.yml
  tags:
    - zookeeper-config

- name: Run the systemd service role
  include_role:
    name: systemd_service
  vars:
    systemd_user_name: "{{ zookeeper_system_user_name }}"
    systemd_group_name: "{{ zookeeper_system_group_name }}"
    systemd_tempd_prefix: openstack
    systemd_slice_name: zookeeper
    systemd_lock_path: /var/lock/zookeeper
    systemd_CPUAccounting: true
    systemd_BlockIOAccounting: true
    systemd_MemoryAccounting: true
    systemd_TasksAccounting: true
    systemd_services:
      - service_name: "{{ zookeeper_service['name'] }}"
        enabled: yes
        state: stopped
        execstarts: "{{ zookeeper_service['execstarts'] }}"
        execstops: "{{ zookeeper_service['execstops'] }}"
        config_overrides: "{{ zookeeper_init_config_overrides }}"
  tags:
    - zookeeper-config
    - systemd-service
